blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/5UP3RTH30B4G/Sound-Party#readme
    about: "Read the README before opening a general question."
issue_template:
  - name: Bug report
    path: bug_report.md
  - name: Feature request
    path: feature_request.md
